### ISSUE TITLE
Blob moved to a different tier

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/azure-events-wishlist#51]
## Usecase scenario

Blobs can be moved between 3 ties: [hot, cool, and archive](https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-storage-tiers). This can be done manually, via API, or with a lifecycle management policy. Currently, there's no way to get notified when blobs are moving between the tiers.

**Comment by xyh1** [comment]
In progress

**Comment by markheath** [comment]
Really need this for some upcoming work. Any news on progress?

**Comment by markheath** [comment]
Looks like this may be available now: Microsoft.Storage.BlobTierChanged
https://docs.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?tabs=event-grid-event-schema

**Comment by SeanFeldman** [comment]
Awesome, can finally close the issue after 1.5 years 🎉
