### ISSUE TITLE
Blob Storage lifecycle management executed

### ISSUE THREAD

**Issue by SeanFeldman** [SeanFeldman/azure-events-wishlist#67]
## Usecase scenario

Perform an additional operation(s) on the blobs that have gone through a lifecycle management policy execution.

**Comment by xyh1** [comment]
In progress

**Comment by SeanFeldman** [comment]
Completed https://learn.microsoft.com/en-us/azure/event-grid/event-schema-blob-storage?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=event-grid-event-schema#policy-related-events
