### ISSUE TITLE
Azure Data Factory

### ISSUE THREAD

**Issue by petarvucetin** [SeanFeldman/azure-events-wishlist#68]
## Usecase scenario

Tracking Azure Data Factory Trigger events, Execution events, Life cycle events (Start/Stop/Cancel). 

ADF Execution Summary Event

**Comment by tomkerkhove** [comment]
@SeanFeldman Do you think it's interesting to track these as individual events or just stick to this?

**Comment by SeanFeldman** [comment]
That has crossed my mind last night. I think the PG team would appreciate specific events as each issue potentially would allow the team to dive into clarifications if necessary.

@petarvucetin would you consider to break this issue into discrete ones? As the person who has the context, it would be great to hear the need for each one of those or some usecases where you could benefit from having these events. Thank you 🙇

**Comment by tomkerkhove** [comment]
Thanks @petarvucetin
